---
title: "Group Project Proposal"
author: "Chase McDonald"
date: "2022-10-11"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Dimensions**
```{r}
df = read.csv("UserCarData.csv")
dim(df)
```
**Summary stats**
```{r}
<<<<<<< HEAD
library(tidyverse)

df <- df %>% 
  group_by(Sales_ID) %>% 
  mutate(Sold = sum(sold=='Y'))

df <- df[,-18]
         
#################################################


=======
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(rpart))
suppressPackageStartupMessages(library(doParallel))
suppressPackageStartupMessages(library(rpart.plot))
        
>>>>>>> origin/main
df[sapply(df,is.character)] <- lapply(df[sapply(df,is.character)],as.factor) # Changes all character types to factors for each column
df$year <- as.factor(df$year) # Changes int year to factor year
df$seats <- as.factor(df$seats) # Changes int seats to factor seats
df$mileage <- as.factor(df$mileage) # Changes int mpg to factor mpg

#####################################################


df <- df %>%
  mutate(selling_price = selling_price * 0.01,
<<<<<<< HEAD
         mi_driven = round(km_driven * 0.6213712)) %>%
  select(-c(km_driven)) # Converts Rubies to Dollars, Converts Km to Miles, and removes the Km column

names(df) <- tolower(names(df))
summary(df) 
=======
         mi_driven = round(km_driven * 0.6213712),
         max_power = as.integer(max_power),
         mileage = as.integer(mileage),
         selling_price = as.integer(selling_price)) %>%
  select(-c(km_driven,torque)) # Converts Rubies to Dollars, Converts Km to Miles, and removes the Km column. Removed Torque until we can figure out what to do with it



df <- df[,-1]
train.rows <- sample(1:nrow(df), 0.70*nrow(df))
TRAIN <- df[train.rows,]
HOLDOUT <- df[-train.rows,]

infodensity <- nearZeroVar(df, saveMetrics= TRUE); infodensity
fitControl <- trainControl(method = "cv", number = 10, classProbs = TRUE, allowParallel = TRUE, verboseIter = FALSE)
>>>>>>> origin/main
```
**Data structure**

```{r}
summary(df)
glimpse(df)
```
**some pretty graphs**

```{r}
library(ggplot2)
library(gridExtra)
library(ggthemes)

selling_price <- df %>% 
  group_by(Sold) %>% 
  summarise(Avg.Price = mean(selling_price))

barplot<- ggplot(selling_price, aes(x = as.factor(Sold), y =Avg.Price )) + geom_bar(stat = 'identity') + theme_wsj() + labs(title = 'Price of sold vs. not sold', y= 'Price' ); barplot

###############################################################3

location <- df %>% 
  group_by(State.or.Province) %>% 
  summarise(Avg.Price = mean(selling_price))  

##################################################################

box <- ggplot(df, aes(x=selling_price)) + geom_histogram() + theme_wsj() + labs(title = 'Distribution of Price'); box
  

print(grid.arrange(barplot,box, ncol =2))
```


```{r}
GLM <- train(sold ~., data = TRAIN, method = "glm", trControl = fitControl, preProc = c("center","scale"))

GLM$results

postResample(predict(GLM,newdata = HOLDOUT), HOLDOUT$sold)
varImp(GLM)
```

```{r}
glmnetGrid <- expand.grid(alpha = seq(0,1,.05),lambda = 10^seq(-4,-1,length=10))

GLMnet <- train(sold~.,data=TRAIN,method='glmnet', tuneGrid=glmnetGrid, trControl=fitControl, preProc = c("center", "scale"))

plot(GLMnet)

GLMnet$results[rownames(GLMnet$bestTune),]

postResample(predict(GLMnet,newdata=HOLDOUT),HOLDOUT$sold)

varImp(GLMnet)
```

```{r}
treeGrid <- expand.grid(cp=10^seq(-5,-1,length=25))

cluster <- makeCluster(detectCores() - 1)
registerDoParallel(cluster) 

TREE <- train(sold~.,data=TRAIN,method='rpart', tuneGrid=treeGrid,trControl=fitControl, preProc = c("center", "scale"))
stopCluster(cluster) 
registerDoSEQ() 

plot(TREE) 

TREE$results[rownames(TREE$bestTune),] 

varImp(TREE)
postResample(predict(TREE,newdata=HOLDOUT),HOLDOUT$sold)

TREE <- rpart(sold ~.,data = TRAIN,cp = 0.002154435)
rpart.plot(TREE)
```

```{r}
forestGrid <- expand.grid(mtry=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16)) 

cluster <- makeCluster(detectCores() - 1)
registerDoParallel(cluster) 

FOREST <- train(sold ~.,data=TRAIN,method='rf',tuneGrid=forestGrid, trControl=fitControl, preProc = c("center", "scale"))
stopCluster(cluster) 
registerDoSEQ() 

plot(FOREST) 
FOREST$results[rownames(FOREST$bestTune),]
postResample(predict(FOREST,newdata=HOLDOUT),HOLDOUT$sold)
varImp(FOREST)
```

```{r}
svmLinearGrid <- expand.grid(C=2^(1:2) )

cluster <- makeCluster(detectCores() - 1)
registerDoParallel(cluster) 
SVM <- train(sold~.,data=TRAIN,method='svmLinear', trControl=fitControl,tuneGrid = svmLinearGrid, preProc = c("center", "scale"))
stopCluster(cluster) 
registerDoSEQ() 

plot(SVM) 

SVM$results[rownames(SVM$bestTune),] 

postResample(predict(SVM,newdata=HOLDOUT),HOLDOUT$sold)
```

```{r}
knnGrid <- expand.grid(k=1:50)

cluster <- makeCluster(detectCores() - 1)
registerDoParallel(cluster) 
KNN <- train(sold~.,data=TRAIN, method='knn', trControl=fitControl,tuneGrid=knnGrid,preProc = c("center", "scale"))

stopCluster(cluster) 
registerDoSEQ() 
plot(KNN)

KNN$results[rownames(KNN$bestTune),]
varImp(KNN)
postResample(predict(KNN, newdata = HOLDOUT), HOLDOUT$sold)
```

```{r}
svmPolyGrid <- expand.grid(degree=1:5, scale=10^seq(-4,-1,by=1), C=2^(2:5) )

cluster <- makeCluster(detectCores() - 1) 
registerDoParallel(cluster) 

SVMpoly <- train(sold~.,data=TRAIN,method='svmPoly', trControl=fitControl,tuneGrid = svmPolyGrid,preProc = c("center", "scale"))
stopCluster(cluster) 
registerDoSEQ() 

plot(SVMpoly) 

SVMpoly$results[rownames(SVMpoly$bestTune),]

postResample(predict(SVMpoly,newdata=HOLDOUT),HOLDOUT$sold)

varImp(SVMpoly)
```

```{r}
svmRadialGrid <- expand.grid(sigma=10^seq(-1,5,by=1), C=2^(0:12) )

cluster <- makeCluster(detectCores() - 1) 
registerDoParallel(cluster) 
SVMradial <- train(sold~.,data=TRAIN,method='svmRadial', trControl=fitControl, tuneGrid = svmRadialGrid, preProc = c("center", "scale"))
stopCluster(cluster) 
registerDoSEQ() 

plot(SVMradial) 

SVMradial$results[rownames(SVMradial$bestTune),]
postResample(predict(SVMradial,newdata=HOLDOUT),HOLDOUT$sold)

varImp(SVMradial)

```

```{r}
nnetGrid <- expand.grid(size=1:6,decay=10^( seq(-5,5,length=10) ) )

cluster <- makeCluster(detectCores() - 1) 
registerDoParallel(cluster) 
NNET <- train(sold~.,data=TRAIN,method='nnet',trControl=fitControl,tuneGrid=nnetGrid, trace=FALSE,linout=FALSE,preProc = c("center", "scale"))
stopCluster(cluster) 
registerDoSEQ() 

plot(NNET)

NNET$results[rownames(NNET$bestTune),] 
postResample(predict(NNET,newdata=HOLDOUT),HOLDOUT$sold) 

varImp(NNET)

```

```{r}
gbmGrid <- expand.grid(n.trees=c(100,200,500,750,1000,1500),interaction.depth=1:15,shrinkage=c(.01,.001),n.minobsinnode=1:10)

cluster <- makeCluster(detectCores() - 1)
registerDoParallel(cluster) 
GBM <- train(sold~.,data=TRAIN, method='gbm',tuneGrid=gbmGrid,verbose=FALSE, trControl=fitControl, preProc = c("center", "scale"))
stopCluster(cluster) 
registerDoSEQ()

GBM$results[rownames(GBM$bestTune),] 
postResample(predict(GBM,newdata=HOLDOUT),HOLDOUT$sold) 

varImp(GBM)

plot(GBM) 
```

```{r}
xgboostGrid <- expand.grid(eta=c(0.1,0.001),nrounds=c(50,100,200,500,1000,1500),max_depth=1:5, min_child_weight=1, gamma=c(.1,.5,0,1,5,10), colsample_bytree=c(0.6,0.8,1), subsample=c(0.6,0.8,1.0))

cluster <- makeCluster(detectCores() - 1)
registerDoParallel(cluster) 

XTREME <- train(Quality~.,data=TRAIN, method="xgbTree", trControl=fitControl, tuneGrid=xgboostGrid, preProc = c("center", "scale"), verbose=FALSE)
stopCluster(cluster) 
registerDoSEQ() 

XTREME$results[rownames(XTREME$bestTune),] 
postResample(predict(XTREME,newdata=HOLDOUT),HOLDOUT$sold) 

varImp(XTREME)

plot(XTREME) 
```

